services:
  - type: web
    name: esono-parser
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PARSER_API_KEY
        sync: false
    healthCheckPath: /health
    plan: starter  # 7$/month, always on
